apiVersion: v1
kind: Service
metadata:
  name: spring-auth0
spec:
  selector:
    name: spring-auth0
  ports:
    - name: http
      port: 8081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: postgesql
spec:
  selector:
    name: postgres-auth
  ports:
    - name: postgre-auth-port
      port: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: port-show
spec:
  selector:
    name: port-show
  ports:
    - name: port-show
      port: 5010
  type: ClusterIP
