apiVersion: v1
kind: Service
metadata:
  name: spring-auth0
spec:
  selector:
    name: spring-auth0
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webappstuf

spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services or
  # maybe external users to connect to (browser)
  type: NodePort
  selector:
    app: webapp-react

  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
