apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-auth0

spec:
  selector:
    matchLabels:
      name: spring-auth0
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-auth0
    spec:
      containers:
        - name: spring-auth0
          image: auth-service
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
              name: auth-service
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
            - name: SPRING_DATASOURCE_URL
              value: spring-auth0/jwt_security
            - name: SPRING_DATASOURCE_USERNAME
              value: root
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth

spec:
  selector:
    matchLabels:
      name: postgres-auth
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres-auth
    spec:
      containers:
        - name: postgres-auth
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: postgresql
          envFrom:
            - configMapRef:
                name: postgres-auth-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-auth-pv-claim
