spring:
  sql:
    init:
      mode: always
  cloud:
    gcp:
      project-id: gclouadfunctionstry0
      credentials:
        location: gclouadfunctionstry0-918d858115d7.json
      sql:
        database-name: test0
        instance-connection-name: gclouadfunctionstry0:europe-west9:stuf-test0
#34.163.137.87
  datasource:
#    url: jdbc:postgresql://34.163.137.87/jwt_security
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
